-- 10_load_unit_children.sql
-- Phase 2: unit-level child tables.
-- vevent, vpicdecode and vpictrailerdecode reference crash_unit (05) because
-- they include parked/working units; vevent also references cevent (08); vsoe
-- references vevent. VINDECODEDON text (YYYY-MM-DD HH:MM:SS) goes into
-- DATETIME unchanged.
--
-- Run from the repository root (see 01_load_staging_tables.sql for the full sequence):
--   mysql -u root -p < sql/load/10_load_unit_children.sql

SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET SESSION sql_mode = 'STRICT_ALL_TABLES,ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

START TRANSACTION;

CALL fars_stage.assert_true(@@SESSION.foreign_key_checks = 1, 'foreign_key_checks must stay ON');
CALL fars_stage.assert_true((SELECT COUNT(*) FROM fars_stage.load_log) = 39, 'Run 02_load_staging_data.sql first: staging is incomplete');
CALL fars_stage.assert_true((SELECT COUNT(*) FROM `fars`.`vevent`) = 0, 'fars.vevent must be empty before loading');
CALL fars_stage.assert_true((SELECT COUNT(*) FROM `fars`.`vsoe`) = 0, 'fars.vsoe must be empty before loading');
CALL fars_stage.assert_true((SELECT COUNT(*) FROM `fars`.`vpicdecode`) = 0, 'fars.vpicdecode must be empty before loading');
CALL fars_stage.assert_true((SELECT COUNT(*) FROM `fars`.`vpictrailerdecode`) = 0, 'fars.vpictrailerdecode must be empty before loading');

-- vevent: 120,270 rows expected.
-- Not loaded from data/processed/vevent.csv: STATE, VNUMBER1, AOI1, SOE,
-- VNUMBER2, AOI2.
-- Reason: STATE is a copy of accident.STATE. VNUMBER1, AOI1, SOE, VNUMBER2
-- and AOI2 duplicate cevent for the same (ST_CASE, EVENTNUM) (D6).
INSERT INTO `fars`.`vevent` (
  `ST_CASE`, `EVENTNUM`, `VEH_NO`, `VEVENTNUM`
)
SELECT
  NULLIF(s.`ST_CASE`, '') AS `ST_CASE`,
  NULLIF(s.`EVENTNUM`, '') AS `EVENTNUM`,
  NULLIF(s.`VEH_NO`, '') AS `VEH_NO`,
  NULLIF(s.`VEVENTNUM`, '') AS `VEVENTNUM`
FROM `fars_stage`.`vevent` AS s;

-- vsoe: 120,270 rows expected.
-- Not loaded from data/processed/vsoe.csv: STATE.
-- Reason: STATE is a copy of accident.STATE.
INSERT INTO `fars`.`vsoe` (
  `ST_CASE`, `VEH_NO`, `VEVENTNUM`, `SOE`, `AOI`
)
SELECT
  NULLIF(s.`ST_CASE`, '') AS `ST_CASE`,
  NULLIF(s.`VEH_NO`, '') AS `VEH_NO`,
  NULLIF(s.`VEVENTNUM`, '') AS `VEVENTNUM`,
  NULLIF(s.`SOE`, '') AS `SOE`,
  NULLIF(s.`AOI`, '') AS `AOI`
FROM `fars_stage`.`vsoe` AS s;

-- vpicdecode: 55,087 rows expected.
-- Not loaded from data/processed/vpicdecode.csv: STATE, VEHICLETYPE,
-- MANUFACTURERFULLNAME, MAKE, MODEL, PLANTCOUNTRY, DESTINATIONMARKET,
-- BODYCLASS, WHEELBASETYPE, GROSSVEHICLEWEIGHTRATINGFROM,
-- GROSSVEHICLEWEIGHTRATINGTO, TRUCKBODYCABTYPE, TRUCKBEDTYPE, BUSTYPE,
-- BUSFLOORCONFIGURATIONTYPE, CUSTOMMOTORCYCLETYPE, MOTORCYCLESUSPENSIONTYPE,
-- MOTORCYCLECHASSISTYPE, STEERINGLOCATION, ENTERTAINMENTSYSTEM,
-- TRANSMISSIONSTYLE, DRIVETYPE, AXLECONFIGURATION, BRAKESYSTEMTYPE,
-- EVDRIVEUNIT, BATTERYTYPE, CHARGERLEVEL, ENGINECONFIGURATION,
-- ENGINECOOLINGTYPE, FUELTYPEPRIMARY, FUELTYPESECONDARY,
-- FUELDELIVERYINJECTIONTYPE, ENGINEVALVETRAINDESIGN,
-- ENGINEELECTRIFICATIONLEVEL, ENGINETURBO, SEATBELTTYPE, PRETENSIONER,
-- AIRBAGLOCFRONT, AIRBAGLOCKNEE, AIRBAGLOCSIDE, AIRBAGLOCCURTAIN,
-- AIRBAGLOCSEATCUSHION, FORWARDCOLLISIONWARNING, DYNAMICBRAKESUPPORT,
-- CRASHIMMINENTBRAKING, PEDESTRIANAUTOEMERGENCYBRAKING, BLINDSPOTWARNING,
-- BLINDSPOTINTERVENTION, LANEDEPARTUREWARNING, LANEKEEPINGASSISTANCE,
-- LANECENTERINGASSISTANCE, BACKUPCAMERA, REARCROSSTRAFFICALERT,
-- REARAUTOMATICEMERGENCYBRAKING, PARKASSIST, DAYTIMERUNNINGLIGHT,
-- HEADLAMPLIGHTSOURCE, SEMIAUTOHEADLAMPBEAMSWITCHING, ADAPTIVEDRIVINGBEAM,
-- ADAPTIVECRUISECONTROL, ANTILOCKBRAKESYSTEM, ELECTRONICSTABILITYCONTROL,
-- TPMS, AUTOMATICCRASHNOTIFICATION, EVENTDATARECORDER, TRACTIONCONTROL,
-- AUTOPEDESTRIANALERTINGSOUND, KEYLESSIGNITION, AUTOREVERSESYSTEM.
-- Reason: STATE is a copy of accident.STATE. the 68 label columns paired with
-- *ID columns live in vpic_labels.
INSERT INTO `fars`.`vpicdecode` (
  `ST_CASE`, `VEH_NO`, `VEHICLEDESCRIPTOR`, `VINDECODEDON`, `VINDECODEERROR`,
  `VEHICLETYPEID`, `MANUFACTURERFULLNAMEID`, `MAKEID`, `MODELID`,
  `MODELYEAR`, `SERIES`, `TRIM`, `SERIES2`, `TRIM2`, `PLANTCOUNTRYID`,
  `PLANTSTATE`, `PLANTCITY`, `PLANTCOMPANYNAME`, `DESTINATIONMARKETID`,
  `BASEPRICE`, `NOTE`, `BODYCLASSID`, `DOORSCOUNT`, `WINDOWS`,
  `WHEELBASETYPEID`, `TRACKWIDTHIN`, `GROSSVEHICLEWEIGHTRATINGFROMID`,
  `GROSSVEHICLEWEIGHTRATINGTOID`, `CURBWEIGHTLB`, `WHEELBASEIN_FROM`,
  `WHEELBASEIN_TO`, `WHEELSCOUNT`, `WHEELSIZEFRONTIN`, `WHEELSIZEREARIN`,
  `TRUCKBODYCABTYPEID`, `TRUCKBEDTYPEID`, `TRUCKBEDLENGTHIN`, `BUSTYPEID`,
  `BUSFLOORCONFIGURATIONTYPEID`, `BUSLENGTHFT`, `OTHERBUSINFO`,
  `CUSTOMMOTORCYCLETYPEID`, `MOTORCYCLESUSPENSIONTYPEID`,
  `MOTORCYCLECHASSISTYPEID`, `OTHERMOTORCYCLEINFO`, `STEERINGLOCATIONID`,
  `ENTERTAINMENTSYSTEMID`, `SEATSCOUNT`, `SEATROWSCOUNT`,
  `TRANSMISSIONSPEEDS`, `TRANSMISSIONSTYLEID`, `DRIVETYPEID`, `AXLESCOUNT`,
  `AXLECONFIGURATIONID`, `BRAKESYSTEMTYPEID`, `BRAKESYSTEMDESC`,
  `EVDRIVEUNITID`, `BATTERYKWH_FROM`, `BATTERYKWH_TO`, `BATTERYV_FROM`,
  `BATTERYV_TO`, `BATTERYA_FROM`, `BATTERYPACKSPERVEHICLE`,
  `BATTERYMODULESPERPACK`, `BATTERYCELLSPERMODULE`, `BATTERYTYPEID`,
  `OTHERBATTERYINFO`, `CHARGERLEVELID`, `CHARGERPOWERKW`,
  `ENGINEMANUFACTURER`, `ENGINEMODEL`, `ENGINECONFIGURATIONID`,
  `ENGINEPOWERKW`, `ENGINESTROKECYCLES`, `ENGINECYLINDERSCOUNT`,
  `ENGINEBRAKEHP_FROM`, `ENGINEBRAKEHP_TO`, `ENGINECOOLINGTYPEID`,
  `DISPLACEMENTCI`, `DISPLACEMENTCC`, `DISPLACEMENTL`, `FUELTYPEPRIMARYID`,
  `FUELTYPESECONDARYID`, `FUELDELIVERYINJECTIONTYPEID`,
  `ENGINEVALVETRAINDESIGNID`, `ENGINEELECTRIFICATIONLEVELID`,
  `ENGINETURBOID`, `TOPSPEEDMPH`, `OTHERENGINEINFO`, `SEATBELTTYPEID`,
  `PRETENSIONERID`, `AIRBAGLOCFRONTID`, `AIRBAGLOCKNEEID`, `AIRBAGLOCSIDEID`,
  `AIRBAGLOCCURTAINID`, `AIRBAGLOCSEATCUSHIONID`, `OTHERRESTRAINTSYSTEMINFO`,
  `FORWARDCOLLISIONWARNINGID`, `DYNAMICBRAKESUPPORTID`,
  `CRASHIMMINENTBRAKINGID`, `PEDESTRIANAUTOEMERGENCYBRAKINGID`,
  `BLINDSPOTWARNINGID`, `BLINDSPOTINTERVENTIONID`, `LANEDEPARTUREWARNINGID`,
  `LANEKEEPINGASSISTANCEID`, `LANECENTERINGASSISTANCEID`, `BACKUPCAMERAID`,
  `REARCROSSTRAFFICALERTID`, `REARAUTOMATICEMERGENCYBRAKINGID`,
  `PARKASSISTID`, `DAYTIMERUNNINGLIGHTID`, `HEADLAMPLIGHTSOURCEID`,
  `SEMIAUTOHEADLAMPBEAMSWITCHINGID`, `ADAPTIVEDRIVINGBEAMID`,
  `ADAPTIVECRUISECONTROLID`, `ANTILOCKBRAKESYSTEMID`,
  `ELECTRONICSTABILITYCONTROLID`, `TPMSID`, `AUTOMATICCRASHNOTIFICATIONID`,
  `EVENTDATARECORDERID`, `TRACTIONCONTROLID`,
  `AUTOPEDESTRIANALERTINGSOUNDID`, `KEYLESSIGNITIONID`,
  `SAEAUTOMATIONLEVEL_FROM`, `AUTOREVERSESYSTEMID`, `ACTIVESAFETYSYSNOTE`
)
SELECT
  NULLIF(s.`ST_CASE`, '') AS `ST_CASE`,
  NULLIF(s.`VEH_NO`, '') AS `VEH_NO`,
  NULLIF(s.`VEHICLEDESCRIPTOR`, '') AS `VEHICLEDESCRIPTOR`,
  NULLIF(s.`VINDECODEDON`, '') AS `VINDECODEDON`,
  NULLIF(s.`VINDECODEERROR`, '') AS `VINDECODEERROR`,
  NULLIF(s.`VEHICLETYPEID`, '') AS `VEHICLETYPEID`,
  NULLIF(s.`MANUFACTURERFULLNAMEID`, '') AS `MANUFACTURERFULLNAMEID`,
  NULLIF(s.`MAKEID`, '') AS `MAKEID`,
  NULLIF(s.`MODELID`, '') AS `MODELID`,
  NULLIF(s.`MODELYEAR`, '') AS `MODELYEAR`,
  NULLIF(s.`SERIES`, '') AS `SERIES`,
  NULLIF(s.`TRIM`, '') AS `TRIM`,
  NULLIF(s.`SERIES2`, '') AS `SERIES2`,
  NULLIF(s.`TRIM2`, '') AS `TRIM2`,
  NULLIF(s.`PLANTCOUNTRYID`, '') AS `PLANTCOUNTRYID`,
  NULLIF(s.`PLANTSTATE`, '') AS `PLANTSTATE`,
  NULLIF(s.`PLANTCITY`, '') AS `PLANTCITY`,
  NULLIF(s.`PLANTCOMPANYNAME`, '') AS `PLANTCOMPANYNAME`,
  NULLIF(s.`DESTINATIONMARKETID`, '') AS `DESTINATIONMARKETID`,
  NULLIF(s.`BASEPRICE`, '') AS `BASEPRICE`,
  NULLIF(s.`NOTE`, '') AS `NOTE`,
  NULLIF(s.`BODYCLASSID`, '') AS `BODYCLASSID`,
  NULLIF(s.`DOORSCOUNT`, '') AS `DOORSCOUNT`,
  NULLIF(s.`WINDOWS`, '') AS `WINDOWS`,
  NULLIF(s.`WHEELBASETYPEID`, '') AS `WHEELBASETYPEID`,
  NULLIF(s.`TRACKWIDTHIN`, '') AS `TRACKWIDTHIN`,
  NULLIF(s.`GROSSVEHICLEWEIGHTRATINGFROMID`, '') AS `GROSSVEHICLEWEIGHTRATINGFROMID`,
  NULLIF(s.`GROSSVEHICLEWEIGHTRATINGTOID`, '') AS `GROSSVEHICLEWEIGHTRATINGTOID`,
  NULLIF(s.`CURBWEIGHTLB`, '') AS `CURBWEIGHTLB`,
  NULLIF(s.`WHEELBASEIN_FROM`, '') AS `WHEELBASEIN_FROM`,
  NULLIF(s.`WHEELBASEIN_TO`, '') AS `WHEELBASEIN_TO`,
  NULLIF(s.`WHEELSCOUNT`, '') AS `WHEELSCOUNT`,
  NULLIF(s.`WHEELSIZEFRONTIN`, '') AS `WHEELSIZEFRONTIN`,
  NULLIF(s.`WHEELSIZEREARIN`, '') AS `WHEELSIZEREARIN`,
  NULLIF(s.`TRUCKBODYCABTYPEID`, '') AS `TRUCKBODYCABTYPEID`,
  NULLIF(s.`TRUCKBEDTYPEID`, '') AS `TRUCKBEDTYPEID`,
  NULLIF(s.`TRUCKBEDLENGTHIN`, '') AS `TRUCKBEDLENGTHIN`,
  NULLIF(s.`BUSTYPEID`, '') AS `BUSTYPEID`,
  NULLIF(s.`BUSFLOORCONFIGURATIONTYPEID`, '') AS `BUSFLOORCONFIGURATIONTYPEID`,
  NULLIF(s.`BUSLENGTHFT`, '') AS `BUSLENGTHFT`,
  NULLIF(s.`OTHERBUSINFO`, '') AS `OTHERBUSINFO`,
  NULLIF(s.`CUSTOMMOTORCYCLETYPEID`, '') AS `CUSTOMMOTORCYCLETYPEID`,
  NULLIF(s.`MOTORCYCLESUSPENSIONTYPEID`, '') AS `MOTORCYCLESUSPENSIONTYPEID`,
  NULLIF(s.`MOTORCYCLECHASSISTYPEID`, '') AS `MOTORCYCLECHASSISTYPEID`,
  NULLIF(s.`OTHERMOTORCYCLEINFO`, '') AS `OTHERMOTORCYCLEINFO`,
  NULLIF(s.`STEERINGLOCATIONID`, '') AS `STEERINGLOCATIONID`,
  NULLIF(s.`ENTERTAINMENTSYSTEMID`, '') AS `ENTERTAINMENTSYSTEMID`,
  NULLIF(s.`SEATSCOUNT`, '') AS `SEATSCOUNT`,
  NULLIF(s.`SEATROWSCOUNT`, '') AS `SEATROWSCOUNT`,
  NULLIF(s.`TRANSMISSIONSPEEDS`, '') AS `TRANSMISSIONSPEEDS`,
  NULLIF(s.`TRANSMISSIONSTYLEID`, '') AS `TRANSMISSIONSTYLEID`,
  NULLIF(s.`DRIVETYPEID`, '') AS `DRIVETYPEID`,
  NULLIF(s.`AXLESCOUNT`, '') AS `AXLESCOUNT`,
  NULLIF(s.`AXLECONFIGURATIONID`, '') AS `AXLECONFIGURATIONID`,
  NULLIF(s.`BRAKESYSTEMTYPEID`, '') AS `BRAKESYSTEMTYPEID`,
  NULLIF(s.`BRAKESYSTEMDESC`, '') AS `BRAKESYSTEMDESC`,
  NULLIF(s.`EVDRIVEUNITID`, '') AS `EVDRIVEUNITID`,
  NULLIF(s.`BATTERYKWH_FROM`, '') AS `BATTERYKWH_FROM`,
  NULLIF(s.`BATTERYKWH_TO`, '') AS `BATTERYKWH_TO`,
  NULLIF(s.`BATTERYV_FROM`, '') AS `BATTERYV_FROM`,
  NULLIF(s.`BATTERYV_TO`, '') AS `BATTERYV_TO`,
  NULLIF(s.`BATTERYA_FROM`, '') AS `BATTERYA_FROM`,
  NULLIF(s.`BATTERYPACKSPERVEHICLE`, '') AS `BATTERYPACKSPERVEHICLE`,
  NULLIF(s.`BATTERYMODULESPERPACK`, '') AS `BATTERYMODULESPERPACK`,
  NULLIF(s.`BATTERYCELLSPERMODULE`, '') AS `BATTERYCELLSPERMODULE`,
  NULLIF(s.`BATTERYTYPEID`, '') AS `BATTERYTYPEID`,
  NULLIF(s.`OTHERBATTERYINFO`, '') AS `OTHERBATTERYINFO`,
  NULLIF(s.`CHARGERLEVELID`, '') AS `CHARGERLEVELID`,
  NULLIF(s.`CHARGERPOWERKW`, '') AS `CHARGERPOWERKW`,
  NULLIF(s.`ENGINEMANUFACTURER`, '') AS `ENGINEMANUFACTURER`,
  NULLIF(s.`ENGINEMODEL`, '') AS `ENGINEMODEL`,
  NULLIF(s.`ENGINECONFIGURATIONID`, '') AS `ENGINECONFIGURATIONID`,
  NULLIF(s.`ENGINEPOWERKW`, '') AS `ENGINEPOWERKW`,
  NULLIF(s.`ENGINESTROKECYCLES`, '') AS `ENGINESTROKECYCLES`,
  NULLIF(s.`ENGINECYLINDERSCOUNT`, '') AS `ENGINECYLINDERSCOUNT`,
  NULLIF(s.`ENGINEBRAKEHP_FROM`, '') AS `ENGINEBRAKEHP_FROM`,
  NULLIF(s.`ENGINEBRAKEHP_TO`, '') AS `ENGINEBRAKEHP_TO`,
  NULLIF(s.`ENGINECOOLINGTYPEID`, '') AS `ENGINECOOLINGTYPEID`,
  NULLIF(s.`DISPLACEMENTCI`, '') AS `DISPLACEMENTCI`,
  NULLIF(s.`DISPLACEMENTCC`, '') AS `DISPLACEMENTCC`,
  NULLIF(s.`DISPLACEMENTL`, '') AS `DISPLACEMENTL`,
  NULLIF(s.`FUELTYPEPRIMARYID`, '') AS `FUELTYPEPRIMARYID`,
  NULLIF(s.`FUELTYPESECONDARYID`, '') AS `FUELTYPESECONDARYID`,
  NULLIF(s.`FUELDELIVERYINJECTIONTYPEID`, '') AS `FUELDELIVERYINJECTIONTYPEID`,
  NULLIF(s.`ENGINEVALVETRAINDESIGNID`, '') AS `ENGINEVALVETRAINDESIGNID`,
  NULLIF(s.`ENGINEELECTRIFICATIONLEVELID`, '') AS `ENGINEELECTRIFICATIONLEVELID`,
  NULLIF(s.`ENGINETURBOID`, '') AS `ENGINETURBOID`,
  NULLIF(s.`TOPSPEEDMPH`, '') AS `TOPSPEEDMPH`,
  NULLIF(s.`OTHERENGINEINFO`, '') AS `OTHERENGINEINFO`,
  NULLIF(s.`SEATBELTTYPEID`, '') AS `SEATBELTTYPEID`,
  NULLIF(s.`PRETENSIONERID`, '') AS `PRETENSIONERID`,
  NULLIF(s.`AIRBAGLOCFRONTID`, '') AS `AIRBAGLOCFRONTID`,
  NULLIF(s.`AIRBAGLOCKNEEID`, '') AS `AIRBAGLOCKNEEID`,
  NULLIF(s.`AIRBAGLOCSIDEID`, '') AS `AIRBAGLOCSIDEID`,
  NULLIF(s.`AIRBAGLOCCURTAINID`, '') AS `AIRBAGLOCCURTAINID`,
  NULLIF(s.`AIRBAGLOCSEATCUSHIONID`, '') AS `AIRBAGLOCSEATCUSHIONID`,
  NULLIF(s.`OTHERRESTRAINTSYSTEMINFO`, '') AS `OTHERRESTRAINTSYSTEMINFO`,
  NULLIF(s.`FORWARDCOLLISIONWARNINGID`, '') AS `FORWARDCOLLISIONWARNINGID`,
  NULLIF(s.`DYNAMICBRAKESUPPORTID`, '') AS `DYNAMICBRAKESUPPORTID`,
  NULLIF(s.`CRASHIMMINENTBRAKINGID`, '') AS `CRASHIMMINENTBRAKINGID`,
  NULLIF(s.`PEDESTRIANAUTOEMERGENCYBRAKINGID`, '') AS `PEDESTRIANAUTOEMERGENCYBRAKINGID`,
  NULLIF(s.`BLINDSPOTWARNINGID`, '') AS `BLINDSPOTWARNINGID`,
  NULLIF(s.`BLINDSPOTINTERVENTIONID`, '') AS `BLINDSPOTINTERVENTIONID`,
  NULLIF(s.`LANEDEPARTUREWARNINGID`, '') AS `LANEDEPARTUREWARNINGID`,
  NULLIF(s.`LANEKEEPINGASSISTANCEID`, '') AS `LANEKEEPINGASSISTANCEID`,
  NULLIF(s.`LANECENTERINGASSISTANCEID`, '') AS `LANECENTERINGASSISTANCEID`,
  NULLIF(s.`BACKUPCAMERAID`, '') AS `BACKUPCAMERAID`,
  NULLIF(s.`REARCROSSTRAFFICALERTID`, '') AS `REARCROSSTRAFFICALERTID`,
  NULLIF(s.`REARAUTOMATICEMERGENCYBRAKINGID`, '') AS `REARAUTOMATICEMERGENCYBRAKINGID`,
  NULLIF(s.`PARKASSISTID`, '') AS `PARKASSISTID`,
  NULLIF(s.`DAYTIMERUNNINGLIGHTID`, '') AS `DAYTIMERUNNINGLIGHTID`,
  NULLIF(s.`HEADLAMPLIGHTSOURCEID`, '') AS `HEADLAMPLIGHTSOURCEID`,
  NULLIF(s.`SEMIAUTOHEADLAMPBEAMSWITCHINGID`, '') AS `SEMIAUTOHEADLAMPBEAMSWITCHINGID`,
  NULLIF(s.`ADAPTIVEDRIVINGBEAMID`, '') AS `ADAPTIVEDRIVINGBEAMID`,
  NULLIF(s.`ADAPTIVECRUISECONTROLID`, '') AS `ADAPTIVECRUISECONTROLID`,
  NULLIF(s.`ANTILOCKBRAKESYSTEMID`, '') AS `ANTILOCKBRAKESYSTEMID`,
  NULLIF(s.`ELECTRONICSTABILITYCONTROLID`, '') AS `ELECTRONICSTABILITYCONTROLID`,
  NULLIF(s.`TPMSID`, '') AS `TPMSID`,
  NULLIF(s.`AUTOMATICCRASHNOTIFICATIONID`, '') AS `AUTOMATICCRASHNOTIFICATIONID`,
  NULLIF(s.`EVENTDATARECORDERID`, '') AS `EVENTDATARECORDERID`,
  NULLIF(s.`TRACTIONCONTROLID`, '') AS `TRACTIONCONTROLID`,
  NULLIF(s.`AUTOPEDESTRIANALERTINGSOUNDID`, '') AS `AUTOPEDESTRIANALERTINGSOUNDID`,
  NULLIF(s.`KEYLESSIGNITIONID`, '') AS `KEYLESSIGNITIONID`,
  NULLIF(s.`SAEAUTOMATIONLEVEL_FROM`, '') AS `SAEAUTOMATIONLEVEL_FROM`,
  NULLIF(s.`AUTOREVERSESYSTEMID`, '') AS `AUTOREVERSESYSTEMID`,
  NULLIF(s.`ACTIVESAFETYSYSNOTE`, '') AS `ACTIVESAFETYSYSNOTE`
FROM `fars_stage`.`vpicdecode` AS s;

-- vpictrailerdecode: 1,639 rows expected.
-- Not loaded from data/processed/vpictrailerdecode.csv: STATE.
-- Reason: STATE is a copy of accident.STATE.
INSERT INTO `fars`.`vpictrailerdecode` (
  `ST_CASE`, `VEH_NO`, `TRAILER_NO`, `VEHICLEDESCRIPTOR`, `VINDECODEDON`,
  `VINDECODEERROR`, `VEHICLETYPEID`, `VEHICLETYPE`, `MANUFACTURERFULLNAMEID`,
  `MANUFACTURERFULLNAME`, `MAKEID`, `MAKE`, `MODELID`, `MODEL`, `MODELYEAR`,
  `SERIES`, `TRIM`, `PLANTCOUNTRYID`, `PLANTCOUNTRY`, `PLANTSTATE`,
  `PLANTCITY`, `PLANTCOMPANYNAME`, `NOTE`, `BODYCLASSID`, `BODYCLASS`,
  `GROSSVEHICLEWEIGHTRATINGFROMID`, `GROSSVEHICLEWEIGHTRATINGFROM`,
  `GROSSVEHICLEWEIGHTRATINGTOID`, `GROSSVEHICLEWEIGHTRATINGTO`,
  `TRAILERBODYTYPEID`, `TRAILERBODYTYPE`, `TRAILERTYPECONNECTIONID`,
  `TRAILERTYPECONNECTION`, `TRAILERLENGTHFT`, `OTHERTRAILERINFO`,
  `AXLESCOUNT`, `AXLECONFIGURATIONID`, `AXLECONFIGURATION`
)
SELECT
  NULLIF(s.`ST_CASE`, '') AS `ST_CASE`,
  NULLIF(s.`VEH_NO`, '') AS `VEH_NO`,
  NULLIF(s.`TRAILER_NO`, '') AS `TRAILER_NO`,
  NULLIF(s.`VEHICLEDESCRIPTOR`, '') AS `VEHICLEDESCRIPTOR`,
  NULLIF(s.`VINDECODEDON`, '') AS `VINDECODEDON`,
  NULLIF(s.`VINDECODEERROR`, '') AS `VINDECODEERROR`,
  NULLIF(s.`VEHICLETYPEID`, '') AS `VEHICLETYPEID`,
  NULLIF(s.`VEHICLETYPE`, '') AS `VEHICLETYPE`,
  NULLIF(s.`MANUFACTURERFULLNAMEID`, '') AS `MANUFACTURERFULLNAMEID`,
  NULLIF(s.`MANUFACTURERFULLNAME`, '') AS `MANUFACTURERFULLNAME`,
  NULLIF(s.`MAKEID`, '') AS `MAKEID`,
  NULLIF(s.`MAKE`, '') AS `MAKE`,
  NULLIF(s.`MODELID`, '') AS `MODELID`,
  NULLIF(s.`MODEL`, '') AS `MODEL`,
  NULLIF(s.`MODELYEAR`, '') AS `MODELYEAR`,
  NULLIF(s.`SERIES`, '') AS `SERIES`,
  NULLIF(s.`TRIM`, '') AS `TRIM`,
  NULLIF(s.`PLANTCOUNTRYID`, '') AS `PLANTCOUNTRYID`,
  NULLIF(s.`PLANTCOUNTRY`, '') AS `PLANTCOUNTRY`,
  NULLIF(s.`PLANTSTATE`, '') AS `PLANTSTATE`,
  NULLIF(s.`PLANTCITY`, '') AS `PLANTCITY`,
  NULLIF(s.`PLANTCOMPANYNAME`, '') AS `PLANTCOMPANYNAME`,
  NULLIF(s.`NOTE`, '') AS `NOTE`,
  NULLIF(s.`BODYCLASSID`, '') AS `BODYCLASSID`,
  NULLIF(s.`BODYCLASS`, '') AS `BODYCLASS`,
  NULLIF(s.`GROSSVEHICLEWEIGHTRATINGFROMID`, '') AS `GROSSVEHICLEWEIGHTRATINGFROMID`,
  NULLIF(s.`GROSSVEHICLEWEIGHTRATINGFROM`, '') AS `GROSSVEHICLEWEIGHTRATINGFROM`,
  NULLIF(s.`GROSSVEHICLEWEIGHTRATINGTOID`, '') AS `GROSSVEHICLEWEIGHTRATINGTOID`,
  NULLIF(s.`GROSSVEHICLEWEIGHTRATINGTO`, '') AS `GROSSVEHICLEWEIGHTRATINGTO`,
  NULLIF(s.`TRAILERBODYTYPEID`, '') AS `TRAILERBODYTYPEID`,
  NULLIF(s.`TRAILERBODYTYPE`, '') AS `TRAILERBODYTYPE`,
  NULLIF(s.`TRAILERTYPECONNECTIONID`, '') AS `TRAILERTYPECONNECTIONID`,
  NULLIF(s.`TRAILERTYPECONNECTION`, '') AS `TRAILERTYPECONNECTION`,
  NULLIF(s.`TRAILERLENGTHFT`, '') AS `TRAILERLENGTHFT`,
  NULLIF(s.`OTHERTRAILERINFO`, '') AS `OTHERTRAILERINFO`,
  NULLIF(s.`AXLESCOUNT`, '') AS `AXLESCOUNT`,
  NULLIF(s.`AXLECONFIGURATIONID`, '') AS `AXLECONFIGURATIONID`,
  NULLIF(s.`AXLECONFIGURATION`, '') AS `AXLECONFIGURATION`
FROM `fars_stage`.`vpictrailerdecode` AS s;

COMMIT;
