-- 01_create_tables.sql
-- MySQL 8 DDL for the FARS 2024 database.
-- Schema source: docs/schema/relational-schema.md (53 relations).
-- Tables are created in dependency order with their foreign keys inline.
-- Run files in sql/schema/ in numeric order, then sql/load/.

CREATE DATABASE IF NOT EXISTS fars DEFAULT CHARACTER SET utf8mb4;
USE fars;

-- ----------------------------------------------------------------------
-- Reference and lookup tables (no dependencies; lookups are reference-only, no FKs)
-- ----------------------------------------------------------------------

-- calendar: one row per date (3NF: (YEAR, MONTH, DAY) -> DAY_WEEK)
CREATE TABLE `calendar` (
  `YEAR`     SMALLINT UNSIGNED NOT NULL,
  `MONTH`    TINYINT UNSIGNED NOT NULL,
  `DAY`      TINYINT UNSIGNED NOT NULL,
  `DAY_WEEK` TINYINT UNSIGNED,
  PRIMARY KEY (`YEAR`, `MONTH`, `DAY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- death_time: 3NF: (DEATH_HR, DEATH_MN) -> DEATH_TM
CREATE TABLE `death_time` (
  `DEATH_HR` TINYINT UNSIGNED NOT NULL,
  `DEATH_MN` TINYINT UNSIGNED NOT NULL,
  `DEATH_TM` SMALLINT UNSIGNED,
  PRIMARY KEY (`DEATH_HR`, `DEATH_MN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- vin_detail: 3NF: VIN -> VIN_1..VIN_12
CREATE TABLE `vin_detail` (
  `VIN`    VARCHAR(12) NOT NULL,
  `VIN_1`  CHAR(1),
  `VIN_2`  CHAR(1),
  `VIN_3`  CHAR(1),
  `VIN_4`  CHAR(1),
  `VIN_5`  CHAR(1),
  `VIN_6`  CHAR(1),
  `VIN_7`  CHAR(1),
  `VIN_8`  CHAR(1),
  `VIN_9`  CHAR(1),
  `VIN_10` CHAR(1),
  `VIN_11` CHAR(1),
  `VIN_12` CHAR(1),
  PRIMARY KEY (`VIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- pvin_detail: 3NF: PVIN -> PVIN_1..PVIN_12
CREATE TABLE `pvin_detail` (
  `PVIN`    VARCHAR(12) NOT NULL,
  `PVIN_1`  CHAR(1),
  `PVIN_2`  CHAR(1),
  `PVIN_3`  CHAR(1),
  `PVIN_4`  CHAR(1),
  `PVIN_5`  CHAR(1),
  `PVIN_6`  CHAR(1),
  `PVIN_7`  CHAR(1),
  `PVIN_8`  CHAR(1),
  `PVIN_9`  CHAR(1),
  `PVIN_10` CHAR(1),
  `PVIN_11` CHAR(1),
  `PVIN_12` CHAR(1),
  PRIMARY KEY (`PVIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- vpic_labels: 68 vPIC *ID -> label pairs; reference only, no FKs
CREATE TABLE `vpic_labels` (
  `attribute` VARCHAR(64) NOT NULL,
  `id`        SMALLINT UNSIGNED NOT NULL,
  `label`     VARCHAR(255),
  PRIMARY KEY (`attribute`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- state_region: 3NF: STATE -> A_REGION
CREATE TABLE `state_region` (
  `STATE`    TINYINT UNSIGNED NOT NULL,
  `A_REGION` TINYINT UNSIGNED,
  PRIMARY KEY (`STATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- roadfc_inter: 3NF: A_ROADFC -> A_INTER
CREATE TABLE `roadfc_inter` (
  `A_ROADFC` TINYINT UNSIGNED NOT NULL,
  `A_INTER`  TINYINT UNSIGNED,
  PRIMARY KEY (`A_ROADFC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- junc_intsec: 3NF: A_JUNC -> A_INTSEC
CREATE TABLE `junc_intsec` (
  `A_JUNC`   TINYINT UNSIGNED NOT NULL,
  `A_INTSEC` TINYINT UNSIGNED,
  PRIMARY KEY (`A_JUNC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- age_band_map: 3NF: A_AGE3 -> A_AGE1, A_AGE2, A_AGE4, A_AGE5, A_AGE9
CREATE TABLE `age_band_map` (
  `A_AGE3` TINYINT UNSIGNED NOT NULL,
  `A_AGE1` TINYINT UNSIGNED,
  `A_AGE2` TINYINT UNSIGNED,
  `A_AGE4` TINYINT UNSIGNED,
  `A_AGE5` TINYINT UNSIGNED,
  `A_AGE9` TINYINT UNSIGNED,
  PRIMARY KEY (`A_AGE3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ped_crash_group: 3NF: PEDCTYPE -> PEDCGP
CREATE TABLE `ped_crash_group` (
  `PEDCTYPE` SMALLINT UNSIGNED NOT NULL,
  `PEDCGP`   SMALLINT UNSIGNED,
  PRIMARY KEY (`PEDCTYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- bike_crash_group: 3NF: BIKECTYPE -> BIKECGP
CREATE TABLE `bike_crash_group` (
  `BIKECTYPE` SMALLINT UNSIGNED NOT NULL,
  `BIKECGP`   SMALLINT UNSIGNED,
  PRIMARY KEY (`BIKECTYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- code_labels: generic code -> label lookup; reference only, no FKs
CREATE TABLE `code_labels` (
  `column` VARCHAR(32) NOT NULL,
  `code`   VARCHAR(12) NOT NULL,
  `label`  VARCHAR(255),
  PRIMARY KEY (`column`, `code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- county: county names; county codes repeat across states
CREATE TABLE `county` (
  `STATE`       TINYINT UNSIGNED NOT NULL,
  `COUNTY`      SMALLINT UNSIGNED NOT NULL,
  `county_name` VARCHAR(32),
  PRIMARY KEY (`STATE`, `COUNTY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- city: city names; city codes repeat across states
CREATE TABLE `city` (
  `STATE`     TINYINT UNSIGNED NOT NULL,
  `CITY`      SMALLINT UNSIGNED NOT NULL,
  `city_name` VARCHAR(64),
  PRIMARY KEY (`STATE`, `CITY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------
-- Crash
-- ----------------------------------------------------------------------

-- accident: one row per crash
CREATE TABLE `accident` (
  `ST_CASE`    INT UNSIGNED NOT NULL,
  `ARR_HOUR`   TINYINT UNSIGNED,
  `ARR_MIN`    TINYINT UNSIGNED,
  `CITY`       SMALLINT UNSIGNED,
  `COUNTY`     SMALLINT UNSIGNED,
  `DAY`        TINYINT UNSIGNED,
  `FATALS`     TINYINT UNSIGNED,
  `FUNC_SYS`   TINYINT UNSIGNED,
  `HARM_EV`    TINYINT UNSIGNED,
  `HOSP_HR`    TINYINT UNSIGNED,
  `HOSP_MN`    TINYINT UNSIGNED,
  `HOUR`       TINYINT UNSIGNED,
  `LATITUDE`   DECIMAL(10,8),
  `LGT_COND`   TINYINT UNSIGNED,
  `LONGITUD`   DECIMAL(12,9),
  `MAN_COLL`   TINYINT UNSIGNED,
  `MILEPT`     MEDIUMINT UNSIGNED,
  `MINUTE`     TINYINT UNSIGNED,
  `MONTH`      TINYINT UNSIGNED,
  `NHS`        TINYINT UNSIGNED,
  `NOT_HOUR`   TINYINT UNSIGNED,
  `NOT_MIN`    TINYINT UNSIGNED,
  `PEDS`       TINYINT UNSIGNED,
  `PERMVIT`    TINYINT UNSIGNED,
  `PERNOTMVIT` TINYINT UNSIGNED,
  `PERSONS`    TINYINT UNSIGNED,
  `PVH_INVL`   TINYINT UNSIGNED,
  `RAIL`       CHAR(7),
  `RD_OWNER`   TINYINT UNSIGNED,
  `RELJCT1`    TINYINT UNSIGNED,
  `RELJCT2`    TINYINT UNSIGNED,
  `REL_ROAD`   TINYINT UNSIGNED,
  `ROUTE`      TINYINT UNSIGNED,
  `RUR_URB`    TINYINT UNSIGNED,
  `SCH_BUS`    TINYINT UNSIGNED,
  `SP_JUR`     TINYINT UNSIGNED,
  `STATE`      TINYINT UNSIGNED,
  `TWAY_ID`    VARCHAR(30),
  `TWAY_ID2`   VARCHAR(30),
  `TYP_INT`    TINYINT UNSIGNED,
  `VE_FORMS`   TINYINT UNSIGNED,
  `VE_TOTAL`   TINYINT UNSIGNED,
  `WEATHER`    TINYINT UNSIGNED,
  `WRK_ZONE`   TINYINT UNSIGNED,
  `YEAR`       SMALLINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`),
  KEY `idx_accident_date` (`YEAR`, `MONTH`, `DAY`),
  CONSTRAINT `fk_accident_calendar` FOREIGN KEY (`YEAR`, `MONTH`, `DAY`)
    REFERENCES `calendar` (`YEAR`, `MONTH`, `DAY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------
-- Unit supertype (D5, D9): every in-transport (V) and parked/working (P) unit
-- ----------------------------------------------------------------------

-- crash_unit: unit_type 'V' = in-transport vehicle, 'P' = parked/working vehicle
CREATE TABLE `crash_unit` (
  `ST_CASE`       INT UNSIGNED NOT NULL,
  `VEH_NO`        TINYINT UNSIGNED NOT NULL,
  `unit_type`     CHAR(1) NOT NULL,
  `BODY_TYP`      TINYINT UNSIGNED,
  `EMER_USE`      TINYINT UNSIGNED,
  `FIRE_EXP`      TINYINT UNSIGNED,
  `GVWR_FROM`     TINYINT UNSIGNED,
  `GVWR_TO`       TINYINT UNSIGNED,
  `ICFINALBODY`   SMALLINT UNSIGNED,
  `IMPACT1`       TINYINT UNSIGNED,
  `MAKE`          TINYINT UNSIGNED,
  `MAK_MOD`       MEDIUMINT UNSIGNED,
  `MOD_YEAR`      SMALLINT UNSIGNED,
  `ROLLOVER`      TINYINT UNSIGNED,
  `SPEC_USE`      TINYINT UNSIGNED,
  `TOW_VEH`       TINYINT UNSIGNED,
  `VPICBODYCLASS` SMALLINT UNSIGNED,
  `VPICMAKE`      MEDIUMINT UNSIGNED,
  `VPICMODEL`     MEDIUMINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`),
  CONSTRAINT `chk_crash_unit_type` CHECK (`unit_type` IN ('V', 'P')),
  CONSTRAINT `fk_crash_unit_accident` FOREIGN KEY (`ST_CASE`)
    REFERENCES `accident` (`ST_CASE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------
-- Unit subtypes
-- ----------------------------------------------------------------------

-- vehicle: one row per in-transport vehicle
CREATE TABLE `vehicle` (
  `ST_CASE`       INT UNSIGNED NOT NULL,
  `VEH_NO`        TINYINT UNSIGNED NOT NULL,
  `ACC_TYPE`      TINYINT UNSIGNED,
  `BUS_USE`       TINYINT UNSIGNED,
  `CARGO_BT`      TINYINT UNSIGNED,
  `CDL_STAT`      TINYINT UNSIGNED,
  `DEATHS`        TINYINT UNSIGNED,
  `DEFORMED`      TINYINT UNSIGNED,
  `DR_DRINK`      TINYINT UNSIGNED,
  `DR_HGT`        SMALLINT UNSIGNED,
  `DR_PRES`       TINYINT UNSIGNED,
  `DR_WGT`        SMALLINT UNSIGNED,
  `DR_ZIP`        MEDIUMINT UNSIGNED,
  `FIRST_MO`      TINYINT UNSIGNED,
  `FIRST_YR`      SMALLINT UNSIGNED,
  `HAZ_CNO`       TINYINT UNSIGNED,
  `HAZ_ID`        SMALLINT UNSIGNED,
  `HAZ_INV`       TINYINT UNSIGNED,
  `HAZ_PLAC`      TINYINT UNSIGNED,
  `HAZ_REL`       TINYINT UNSIGNED,
  `HIT_RUN`       TINYINT UNSIGNED,
  `J_KNIFE`       TINYINT UNSIGNED,
  `LAST_MO`       TINYINT UNSIGNED,
  `LAST_YR`       SMALLINT UNSIGNED,
  `L_COMPL`       TINYINT UNSIGNED,
  `L_ENDORS`      TINYINT UNSIGNED,
  `L_RESTRI`      TINYINT UNSIGNED,
  `L_STATE`       TINYINT UNSIGNED,
  `L_STATUS`      TINYINT UNSIGNED,
  `L_TYPE`        TINYINT UNSIGNED,
  `MCARR_I1`      TINYINT UNSIGNED,
  `MCARR_I2`      VARCHAR(9),
  `MCARR_ID`      VARCHAR(11),
  `MODEL`         SMALLINT UNSIGNED,
  `M_HARM`        TINYINT UNSIGNED,
  `NUMOCCS`       TINYINT UNSIGNED,
  `OWNER`         TINYINT UNSIGNED,
  `PCRASH4`       TINYINT UNSIGNED,
  `PCRASH5`       TINYINT UNSIGNED,
  `PREV_ACC`      SMALLINT UNSIGNED,
  `PREV_DWI`      SMALLINT UNSIGNED,
  `PREV_OTH`      SMALLINT UNSIGNED,
  `PREV_SPD`      SMALLINT UNSIGNED,
  `PREV_SUS1`     SMALLINT UNSIGNED,
  `PREV_SUS2`     SMALLINT UNSIGNED,
  `PREV_SUS3`     SMALLINT UNSIGNED,
  `P_CRASH1`      TINYINT UNSIGNED,
  `P_CRASH2`      TINYINT UNSIGNED,
  `P_CRASH3`      TINYINT UNSIGNED,
  `REG_STAT`      TINYINT UNSIGNED,
  `ROLINLOC`      TINYINT UNSIGNED,
  `SPEEDREL`      TINYINT UNSIGNED,
  `TOWED`         TINYINT UNSIGNED,
  `TRAV_SP`       SMALLINT UNSIGNED,
  `TRLR1GVWR`     TINYINT UNSIGNED,
  `TRLR1VIN`      VARCHAR(12),
  `TRLR2GVWR`     TINYINT UNSIGNED,
  `TRLR2VIN`      VARCHAR(12),
  `TRLR3GVWR`     TINYINT UNSIGNED,
  `TRLR3VIN`      VARCHAR(12),
  `UNDEROVERRIDE` TINYINT UNSIGNED,
  `UNITTYPE`      TINYINT UNSIGNED,
  `VALIGN`        TINYINT UNSIGNED,
  `VIN`           VARCHAR(12),
  `VNUM_LAN`      TINYINT UNSIGNED,
  `VPAVETYP`      TINYINT UNSIGNED,
  `VPROFILE`      TINYINT UNSIGNED,
  `VSPD_LIM`      TINYINT UNSIGNED,
  `VSURCOND`      TINYINT UNSIGNED,
  `VTCONT_F`      TINYINT UNSIGNED,
  `VTRAFCON`      TINYINT UNSIGNED,
  `VTRAFWAY`      TINYINT UNSIGNED,
  `V_CONFIG`      TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`),
  KEY `idx_vehicle_vin` (`VIN`),
  CONSTRAINT `fk_vehicle_accident` FOREIGN KEY (`ST_CASE`)
    REFERENCES `accident` (`ST_CASE`),
  CONSTRAINT `fk_vehicle_crash_unit` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `crash_unit` (`ST_CASE`, `VEH_NO`),
  CONSTRAINT `fk_vehicle_vin_detail` FOREIGN KEY (`VIN`)
    REFERENCES `vin_detail` (`VIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- parkwork: one row per parked/working vehicle
CREATE TABLE `parkwork` (
  `ST_CASE`        INT UNSIGNED NOT NULL,
  `VEH_NO`         TINYINT UNSIGNED NOT NULL,
  `PNUMOCCS`       TINYINT UNSIGNED,
  `PTYPE`          TINYINT UNSIGNED,
  `PHIT_RUN`       TINYINT UNSIGNED,
  `PREG_STAT`      TINYINT UNSIGNED,
  `POWNER`         TINYINT UNSIGNED,
  `PVIN`           VARCHAR(12),
  `PMODYEAR`       SMALLINT UNSIGNED,
  `PVPICMAKE`      MEDIUMINT UNSIGNED,
  `PVPICMODEL`     MEDIUMINT UNSIGNED,
  `PVPICBODYCLASS` SMALLINT UNSIGNED,
  `PMAKE`          TINYINT UNSIGNED,
  `PMODEL`         SMALLINT UNSIGNED,
  `PBODYTYP`       TINYINT UNSIGNED,
  `PICFINALBODY`   SMALLINT UNSIGNED,
  `PGVWR_FROM`     TINYINT UNSIGNED,
  `PGVWR_TO`       TINYINT UNSIGNED,
  `PTRAILER`       TINYINT UNSIGNED,
  `PTRLR1VIN`      VARCHAR(12),
  `PTRLR2VIN`      VARCHAR(12),
  `PTRLR1GVWR`     TINYINT UNSIGNED,
  `PTRLR2GVWR`     TINYINT UNSIGNED,
  `PMCARR_ID`      VARCHAR(11),
  `PMCARR_I1`      TINYINT UNSIGNED,
  `PMCARR_I2`      VARCHAR(9),
  `PV_CONFIG`      TINYINT UNSIGNED,
  `PCARGTYP`       TINYINT UNSIGNED,
  `PBUS_USE`       TINYINT UNSIGNED,
  `PSP_USE`        TINYINT UNSIGNED,
  `PEM_USE`        TINYINT UNSIGNED,
  `PUNDEROVERRIDE` TINYINT UNSIGNED,
  `PIMPACT1`       TINYINT UNSIGNED,
  `PVEH_SEV`       TINYINT UNSIGNED,
  `PTOWED`         TINYINT UNSIGNED,
  `PM_HARM`        TINYINT UNSIGNED,
  `PFIRE`          TINYINT UNSIGNED,
  `PMAK_MOD`       MEDIUMINT UNSIGNED,
  `PDEATHS`        TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`),
  CONSTRAINT `fk_parkwork_accident` FOREIGN KEY (`ST_CASE`)
    REFERENCES `accident` (`ST_CASE`),
  CONSTRAINT `fk_parkwork_crash_unit` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `crash_unit` (`ST_CASE`, `VEH_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------
-- Person (D1: no FK to vehicle; VEH_NO = 0 marks non-motorists)
-- ----------------------------------------------------------------------

CREATE TABLE `person` (
  `ST_CASE`    INT UNSIGNED NOT NULL,
  `VEH_NO`     TINYINT UNSIGNED NOT NULL,
  `PER_NO`     TINYINT UNSIGNED NOT NULL,
  `AGE`        SMALLINT UNSIGNED,
  `AIR_BAG`    TINYINT UNSIGNED,
  `ALC_RES`    SMALLINT UNSIGNED,
  `ALC_STATUS` TINYINT UNSIGNED,
  `ATST_TYP`   TINYINT UNSIGNED,
  `DEATH_DA`   TINYINT UNSIGNED,
  `DEATH_HR`   TINYINT UNSIGNED,
  `DEATH_MN`   TINYINT UNSIGNED,
  `DEATH_MO`   TINYINT UNSIGNED,
  `DEATH_YR`   SMALLINT UNSIGNED,
  `DEVMOTOR`   TINYINT UNSIGNED,
  `DEVTYPE`    TINYINT UNSIGNED,
  `DOA`        TINYINT UNSIGNED,
  `DRINKING`   TINYINT UNSIGNED,
  `DRUGS`      TINYINT UNSIGNED,
  `DSTATUS`    TINYINT UNSIGNED,
  `EJECTION`   TINYINT UNSIGNED,
  `EJ_PATH`    TINYINT UNSIGNED,
  `EXTRICAT`   TINYINT UNSIGNED,
  `HELM_MIS`   TINYINT UNSIGNED,
  `HELM_USE`   TINYINT UNSIGNED,
  `HISPANIC`   TINYINT UNSIGNED,
  `HOSPITAL`   TINYINT UNSIGNED,
  `INJ_SEV`    TINYINT UNSIGNED,
  `LAG_HRS`    SMALLINT UNSIGNED,
  `LAG_MINS`   TINYINT UNSIGNED,
  `LOCATION`   TINYINT UNSIGNED,
  `MULTRACE`   TINYINT UNSIGNED,
  `PER_TYP`    TINYINT UNSIGNED,
  `REST_MIS`   TINYINT UNSIGNED,
  `REST_USE`   TINYINT UNSIGNED,
  `SEAT_POS`   TINYINT UNSIGNED,
  `SEX`        TINYINT UNSIGNED,
  `STR_VEH`    TINYINT UNSIGNED,
  `WORK_INJ`   TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `PER_NO`),
  KEY `idx_person_death_time` (`DEATH_HR`, `DEATH_MN`),
  CONSTRAINT `fk_person_accident` FOREIGN KEY (`ST_CASE`)
    REFERENCES `accident` (`ST_CASE`),
  CONSTRAINT `fk_person_death_time` FOREIGN KEY (`DEATH_HR`, `DEATH_MN`)
    REFERENCES `death_time` (`DEATH_HR`, `DEATH_MN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------
-- Crash-level children
-- ----------------------------------------------------------------------

CREATE TABLE `acc_aux` (
  `ST_CASE`                INT UNSIGNED NOT NULL,
  `A_CRAINJ`               TINYINT UNSIGNED,
  `A_RU`                   TINYINT UNSIGNED,
  `A_RELRD`                TINYINT UNSIGNED,
  `A_ROADFC`               TINYINT UNSIGNED,
  `A_JUNC`                 TINYINT UNSIGNED,
  `A_MANCOL`               TINYINT UNSIGNED,
  `A_TOD`                  TINYINT UNSIGNED,
  `A_DOW`                  TINYINT UNSIGNED,
  `A_CT`                   TINYINT UNSIGNED,
  `A_WEATHER`              TINYINT UNSIGNED,
  `A_LT`                   TINYINT UNSIGNED,
  `A_MC`                   TINYINT UNSIGNED,
  `A_SBUSCR`               TINYINT UNSIGNED,
  `A_SPCRA`                TINYINT UNSIGNED,
  `A_PED`                  TINYINT UNSIGNED,
  `A_PED_F`                TINYINT UNSIGNED,
  `A_PEDAL`                TINYINT UNSIGNED,
  `A_PEDAL_F`              TINYINT UNSIGNED,
  `A_ROLL`                 TINYINT UNSIGNED,
  `A_POLPUR`               TINYINT UNSIGNED,
  `A_POSBAC`               TINYINT UNSIGNED,
  `A_D15_19`               TINYINT UNSIGNED,
  `A_D16_19`               TINYINT UNSIGNED,
  `A_D15_20`               TINYINT UNSIGNED,
  `A_D16_20`               TINYINT UNSIGNED,
  `A_D65PLS`               TINYINT UNSIGNED,
  `A_D21_24`               TINYINT UNSIGNED,
  `A_D16_24`               TINYINT UNSIGNED,
  `A_RD`                   TINYINT UNSIGNED,
  `A_HR`                   TINYINT UNSIGNED,
  `A_DIST`                 TINYINT UNSIGNED,
  `A_DROWSY`               TINYINT UNSIGNED,
  `A_WRONGWAY`             TINYINT UNSIGNED,
  `BIA`                    TINYINT UNSIGNED,
  `SPJ_INDIAN`             TINYINT UNSIGNED,
  `INDIAN_RES`             TINYINT UNSIGNED,
  `CENSUS_2020_TRACT_FIPS` CHAR(11),
  `TRACT`                  TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`),
  CONSTRAINT `fk_acc_aux_accident` FOREIGN KEY (`ST_CASE`)
    REFERENCES `accident` (`ST_CASE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cevent` (
  `ST_CASE`  INT UNSIGNED NOT NULL,
  `EVENTNUM` TINYINT UNSIGNED NOT NULL,
  `VNUMBER1` TINYINT UNSIGNED,
  `AOI1`     TINYINT UNSIGNED,
  `SOE`      TINYINT UNSIGNED,
  `VNUMBER2` SMALLINT UNSIGNED,
  `AOI2`     TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`, `EVENTNUM`),
  CONSTRAINT `fk_cevent_accident` FOREIGN KEY (`ST_CASE`)
    REFERENCES `accident` (`ST_CASE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `crashrf` (
  `ST_CASE` INT UNSIGNED NOT NULL,
  `CRASHRF` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `CRASHRF`),
  CONSTRAINT `fk_crashrf_accident` FOREIGN KEY (`ST_CASE`)
    REFERENCES `accident` (`ST_CASE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `weather` (
  `ST_CASE` INT UNSIGNED NOT NULL,
  `WEATHER` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `WEATHER`),
  CONSTRAINT `fk_weather_accident` FOREIGN KEY (`ST_CASE`)
    REFERENCES `accident` (`ST_CASE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `miacc` (
  `ST_CASE` INT UNSIGNED NOT NULL,
  `A1`      TINYINT UNSIGNED,
  `A2`      TINYINT UNSIGNED,
  `A3`      TINYINT UNSIGNED,
  `A4`      TINYINT UNSIGNED,
  `A5`      TINYINT UNSIGNED,
  `A6`      TINYINT UNSIGNED,
  `A7`      TINYINT UNSIGNED,
  `A8`      TINYINT UNSIGNED,
  `A9`      TINYINT UNSIGNED,
  `A10`     TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`),
  CONSTRAINT `fk_miacc_accident` FOREIGN KEY (`ST_CASE`)
    REFERENCES `accident` (`ST_CASE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `midrvacc` (
  `ST_CASE` INT UNSIGNED NOT NULL,
  `A1`      TINYINT UNSIGNED,
  `A2`      TINYINT UNSIGNED,
  `A3`      TINYINT UNSIGNED,
  `A4`      TINYINT UNSIGNED,
  `A5`      TINYINT UNSIGNED,
  `A6`      TINYINT UNSIGNED,
  `A7`      TINYINT UNSIGNED,
  `A8`      TINYINT UNSIGNED,
  `A9`      TINYINT UNSIGNED,
  `A10`     TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`),
  CONSTRAINT `fk_midrvacc_accident` FOREIGN KEY (`ST_CASE`)
    REFERENCES `accident` (`ST_CASE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- parkwork_hazmat: 2NF: ST_CASE -> PHAZ_*
CREATE TABLE `parkwork_hazmat` (
  `ST_CASE`  INT UNSIGNED NOT NULL,
  `PHAZ_INV` TINYINT UNSIGNED,
  `PHAZPLAC` TINYINT UNSIGNED,
  `PHAZ_ID`  SMALLINT UNSIGNED,
  `PHAZ_CNO` TINYINT UNSIGNED,
  `PHAZ_REL` TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`),
  CONSTRAINT `fk_parkwork_hazmat_accident` FOREIGN KEY (`ST_CASE`)
    REFERENCES `accident` (`ST_CASE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- crash_pbszone: 2NF: ST_CASE -> PBSZONE
CREATE TABLE `crash_pbszone` (
  `ST_CASE` INT UNSIGNED NOT NULL,
  `PBSZONE` TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`),
  CONSTRAINT `fk_crash_pbszone_accident` FOREIGN KEY (`ST_CASE`)
    REFERENCES `accident` (`ST_CASE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------
-- Vehicle-level children
-- ----------------------------------------------------------------------

CREATE TABLE `damage` (
  `ST_CASE` INT UNSIGNED NOT NULL,
  `VEH_NO`  TINYINT UNSIGNED NOT NULL,
  `DAMAGE`  TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `DAMAGE`),
  CONSTRAINT `fk_damage_vehicle` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `vehicle` (`ST_CASE`, `VEH_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `distract` (
  `ST_CASE`    INT UNSIGNED NOT NULL,
  `VEH_NO`     TINYINT UNSIGNED NOT NULL,
  `DRDISTRACT` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `DRDISTRACT`),
  CONSTRAINT `fk_distract_vehicle` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `vehicle` (`ST_CASE`, `VEH_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `drimpair` (
  `ST_CASE`  INT UNSIGNED NOT NULL,
  `VEH_NO`   TINYINT UNSIGNED NOT NULL,
  `DRIMPAIR` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `DRIMPAIR`),
  CONSTRAINT `fk_drimpair_vehicle` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `vehicle` (`ST_CASE`, `VEH_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `driverrf` (
  `ST_CASE`  INT UNSIGNED NOT NULL,
  `VEH_NO`   TINYINT UNSIGNED NOT NULL,
  `DRIVERRF` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `DRIVERRF`),
  CONSTRAINT `fk_driverrf_vehicle` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `vehicle` (`ST_CASE`, `VEH_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `factor` (
  `ST_CASE`   INT UNSIGNED NOT NULL,
  `VEH_NO`    TINYINT UNSIGNED NOT NULL,
  `VEHICLECC` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `VEHICLECC`),
  CONSTRAINT `fk_factor_vehicle` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `vehicle` (`ST_CASE`, `VEH_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `maneuver` (
  `ST_CASE`  INT UNSIGNED NOT NULL,
  `VEH_NO`   TINYINT UNSIGNED NOT NULL,
  `MANEUVER` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `MANEUVER`),
  CONSTRAINT `fk_maneuver_vehicle` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `vehicle` (`ST_CASE`, `VEH_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `vehiclesf` (
  `ST_CASE`   INT UNSIGNED NOT NULL,
  `VEH_NO`    TINYINT UNSIGNED NOT NULL,
  `VEHICLESF` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `VEHICLESF`),
  CONSTRAINT `fk_vehiclesf_vehicle` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `vehicle` (`ST_CASE`, `VEH_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `violatn` (
  `ST_CASE`   INT UNSIGNED NOT NULL,
  `VEH_NO`    TINYINT UNSIGNED NOT NULL,
  `VIOLATION` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `VIOLATION`),
  CONSTRAINT `fk_violatn_vehicle` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `vehicle` (`ST_CASE`, `VEH_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `vision` (
  `ST_CASE` INT UNSIGNED NOT NULL,
  `VEH_NO`  TINYINT UNSIGNED NOT NULL,
  `VISION`  TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `VISION`),
  CONSTRAINT `fk_vision_vehicle` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `vehicle` (`ST_CASE`, `VEH_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `veh_aux` (
  `ST_CASE`       INT UNSIGNED NOT NULL,
  `VEH_NO`        TINYINT UNSIGNED NOT NULL,
  `A_WRONGWAYDRV` TINYINT UNSIGNED,
  `A_DRDIS`       TINYINT UNSIGNED,
  `A_DRDRO`       TINYINT UNSIGNED,
  `A_VRD`         TINYINT UNSIGNED,
  `A_BODY`        TINYINT UNSIGNED,
  `A_IMP1`        TINYINT UNSIGNED,
  `A_VROLL`       TINYINT UNSIGNED,
  `A_LIC_S`       TINYINT UNSIGNED,
  `A_LIC_C`       TINYINT UNSIGNED,
  `A_CDL_S`       TINYINT UNSIGNED,
  `A_MC_L_S`      TINYINT UNSIGNED,
  `A_SPVEH`       TINYINT UNSIGNED,
  `A_SBUS`        TINYINT UNSIGNED,
  `A_MOD_YR`      SMALLINT UNSIGNED,
  `A_FIRE_EXP`    TINYINT UNSIGNED,
  `A_TOWED`       TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`),
  CONSTRAINT `fk_veh_aux_vehicle` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `vehicle` (`ST_CASE`, `VEH_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------
-- Unit-level children (FK to crash_unit, D5) and event chain (D6, D7)
-- ----------------------------------------------------------------------

-- vevent: (unit, event) link; event attributes live in cevent (D6)
CREATE TABLE `vevent` (
  `ST_CASE`   INT UNSIGNED NOT NULL,
  `EVENTNUM`  TINYINT UNSIGNED,
  `VEH_NO`    TINYINT UNSIGNED NOT NULL,
  `VEVENTNUM` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `VEVENTNUM`),
  KEY `idx_vevent_event` (`ST_CASE`, `EVENTNUM`),
  CONSTRAINT `fk_vevent_crash_unit` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `crash_unit` (`ST_CASE`, `VEH_NO`),
  CONSTRAINT `fk_vevent_cevent` FOREIGN KEY (`ST_CASE`, `EVENTNUM`)
    REFERENCES `cevent` (`ST_CASE`, `EVENTNUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- vsoe: PK is (ST_CASE, VEH_NO, VEVENTNUM) (D7)
CREATE TABLE `vsoe` (
  `ST_CASE`   INT UNSIGNED NOT NULL,
  `VEH_NO`    TINYINT UNSIGNED NOT NULL,
  `VEVENTNUM` TINYINT UNSIGNED NOT NULL,
  `SOE`       TINYINT UNSIGNED,
  `AOI`       TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `VEVENTNUM`),
  CONSTRAINT `fk_vsoe_vevent` FOREIGN KEY (`ST_CASE`, `VEH_NO`, `VEVENTNUM`)
    REFERENCES `vevent` (`ST_CASE`, `VEH_NO`, `VEVENTNUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `vpicdecode` (
  `ST_CASE`                          INT UNSIGNED NOT NULL,
  `VEH_NO`                           TINYINT UNSIGNED NOT NULL,
  `VEHICLEDESCRIPTOR`                VARCHAR(32),
  `VINDECODEDON`                     DATETIME,
  `VINDECODEERROR`                   VARCHAR(8),
  `VEHICLETYPEID`                    TINYINT UNSIGNED,
  `MANUFACTURERFULLNAMEID`           SMALLINT UNSIGNED,
  `MAKEID`                           SMALLINT UNSIGNED,
  `MODELID`                          SMALLINT UNSIGNED,
  `MODELYEAR`                        SMALLINT UNSIGNED,
  `SERIES`                           VARCHAR(255),
  `TRIM`                             VARCHAR(255),
  `SERIES2`                          VARCHAR(128),
  `TRIM2`                            VARCHAR(128),
  `PLANTCOUNTRYID`                   TINYINT UNSIGNED,
  `PLANTSTATE`                       VARCHAR(32),
  `PLANTCITY`                        VARCHAR(64),
  `PLANTCOMPANYNAME`                 VARCHAR(64),
  `DESTINATIONMARKETID`              TINYINT UNSIGNED,
  `BASEPRICE`                        DECIMAL(8,2),
  `NOTE`                             VARCHAR(500),
  `BODYCLASSID`                      TINYINT UNSIGNED,
  `DOORSCOUNT`                       TINYINT UNSIGNED,
  `WINDOWS`                          TINYINT UNSIGNED,
  `WHEELBASETYPEID`                  TINYINT UNSIGNED,
  `TRACKWIDTHIN`                     DECIMAL(5,3),
  `GROSSVEHICLEWEIGHTRATINGFROMID`   TINYINT UNSIGNED,
  `GROSSVEHICLEWEIGHTRATINGTOID`     TINYINT UNSIGNED,
  `CURBWEIGHTLB`                     SMALLINT UNSIGNED,
  `WHEELBASEIN_FROM`                 DECIMAL(7,4),
  `WHEELBASEIN_TO`                   DECIMAL(7,4),
  `WHEELSCOUNT`                      TINYINT UNSIGNED,
  `WHEELSIZEFRONTIN`                 TINYINT UNSIGNED,
  `WHEELSIZEREARIN`                  TINYINT UNSIGNED,
  `TRUCKBODYCABTYPEID`               TINYINT UNSIGNED,
  `TRUCKBEDTYPEID`                   TINYINT UNSIGNED,
  `TRUCKBEDLENGTHIN`                 TINYINT UNSIGNED,
  `BUSTYPEID`                        TINYINT UNSIGNED,
  `BUSFLOORCONFIGURATIONTYPEID`      TINYINT UNSIGNED,
  `BUSLENGTHFT`                      TINYINT UNSIGNED,
  `OTHERBUSINFO`                     VARCHAR(128),
  `CUSTOMMOTORCYCLETYPEID`           TINYINT UNSIGNED,
  `MOTORCYCLESUSPENSIONTYPEID`       TINYINT UNSIGNED,
  `MOTORCYCLECHASSISTYPEID`          TINYINT UNSIGNED,
  `OTHERMOTORCYCLEINFO`              VARCHAR(128),
  `STEERINGLOCATIONID`               TINYINT UNSIGNED,
  `ENTERTAINMENTSYSTEMID`            TINYINT UNSIGNED,
  `SEATSCOUNT`                       TINYINT UNSIGNED,
  `SEATROWSCOUNT`                    TINYINT UNSIGNED,
  `TRANSMISSIONSPEEDS`               TINYINT UNSIGNED,
  `TRANSMISSIONSTYLEID`              TINYINT UNSIGNED,
  `DRIVETYPEID`                      TINYINT UNSIGNED,
  `AXLESCOUNT`                       TINYINT UNSIGNED,
  `AXLECONFIGURATIONID`              TINYINT UNSIGNED,
  `BRAKESYSTEMTYPEID`                TINYINT UNSIGNED,
  `BRAKESYSTEMDESC`                  VARCHAR(128),
  `EVDRIVEUNITID`                    TINYINT UNSIGNED,
  `BATTERYKWH_FROM`                  DECIMAL(5,2),
  `BATTERYKWH_TO`                    DECIMAL(5,2),
  `BATTERYV_FROM`                    SMALLINT UNSIGNED,
  `BATTERYV_TO`                      TINYINT UNSIGNED,
  `BATTERYA_FROM`                    TINYINT UNSIGNED,
  `BATTERYPACKSPERVEHICLE`           TINYINT UNSIGNED,
  `BATTERYMODULESPERPACK`            TINYINT UNSIGNED,
  `BATTERYCELLSPERMODULE`            TINYINT UNSIGNED,
  `BATTERYTYPEID`                    TINYINT UNSIGNED,
  `OTHERBATTERYINFO`                 VARCHAR(128),
  `CHARGERLEVELID`                   TINYINT UNSIGNED,
  `CHARGERPOWERKW`                   TINYINT UNSIGNED,
  `ENGINEMANUFACTURER`               VARCHAR(32),
  `ENGINEMODEL`                      VARCHAR(128),
  `ENGINECONFIGURATIONID`            TINYINT UNSIGNED,
  `ENGINEPOWERKW`                    DECIMAL(6,3),
  `ENGINESTROKECYCLES`               TINYINT UNSIGNED,
  `ENGINECYLINDERSCOUNT`             TINYINT UNSIGNED,
  `ENGINEBRAKEHP_FROM`               DECIMAL(8,4),
  `ENGINEBRAKEHP_TO`                 DECIMAL(7,4),
  `ENGINECOOLINGTYPEID`              TINYINT UNSIGNED,
  `DISPLACEMENTCI`                   DECIMAL(5,2),
  `DISPLACEMENTCC`                   DECIMAL(8,3),
  `DISPLACEMENTL`                    DECIMAL(8,6),
  `FUELTYPEPRIMARYID`                TINYINT UNSIGNED,
  `FUELTYPESECONDARYID`              TINYINT UNSIGNED,
  `FUELDELIVERYINJECTIONTYPEID`      TINYINT UNSIGNED,
  `ENGINEVALVETRAINDESIGNID`         TINYINT UNSIGNED,
  `ENGINEELECTRIFICATIONLEVELID`     TINYINT UNSIGNED,
  `ENGINETURBOID`                    TINYINT UNSIGNED,
  `TOPSPEEDMPH`                      TINYINT UNSIGNED,
  `OTHERENGINEINFO`                  VARCHAR(500),
  `SEATBELTTYPEID`                   TINYINT UNSIGNED,
  `PRETENSIONERID`                   TINYINT UNSIGNED,
  `AIRBAGLOCFRONTID`                 TINYINT UNSIGNED,
  `AIRBAGLOCKNEEID`                  TINYINT UNSIGNED,
  `AIRBAGLOCSIDEID`                  TINYINT UNSIGNED,
  `AIRBAGLOCCURTAINID`               TINYINT UNSIGNED,
  `AIRBAGLOCSEATCUSHIONID`           TINYINT UNSIGNED,
  `OTHERRESTRAINTSYSTEMINFO`         VARCHAR(500),
  `FORWARDCOLLISIONWARNINGID`        TINYINT UNSIGNED,
  `DYNAMICBRAKESUPPORTID`            TINYINT UNSIGNED,
  `CRASHIMMINENTBRAKINGID`           TINYINT UNSIGNED,
  `PEDESTRIANAUTOEMERGENCYBRAKINGID` TINYINT UNSIGNED,
  `BLINDSPOTWARNINGID`               TINYINT UNSIGNED,
  `BLINDSPOTINTERVENTIONID`          TINYINT UNSIGNED,
  `LANEDEPARTUREWARNINGID`           TINYINT UNSIGNED,
  `LANEKEEPINGASSISTANCEID`          TINYINT UNSIGNED,
  `LANECENTERINGASSISTANCEID`        TINYINT UNSIGNED,
  `BACKUPCAMERAID`                   TINYINT UNSIGNED,
  `REARCROSSTRAFFICALERTID`          TINYINT UNSIGNED,
  `REARAUTOMATICEMERGENCYBRAKINGID`  TINYINT UNSIGNED,
  `PARKASSISTID`                     TINYINT UNSIGNED,
  `DAYTIMERUNNINGLIGHTID`            TINYINT UNSIGNED,
  `HEADLAMPLIGHTSOURCEID`            TINYINT UNSIGNED,
  `SEMIAUTOHEADLAMPBEAMSWITCHINGID`  TINYINT UNSIGNED,
  `ADAPTIVEDRIVINGBEAMID`            TINYINT UNSIGNED,
  `ADAPTIVECRUISECONTROLID`          TINYINT UNSIGNED,
  `ANTILOCKBRAKESYSTEMID`            TINYINT UNSIGNED,
  `ELECTRONICSTABILITYCONTROLID`     TINYINT UNSIGNED,
  `TPMSID`                           TINYINT UNSIGNED,
  `AUTOMATICCRASHNOTIFICATIONID`     TINYINT UNSIGNED,
  `EVENTDATARECORDERID`              TINYINT UNSIGNED,
  `TRACTIONCONTROLID`                TINYINT UNSIGNED,
  `AUTOPEDESTRIANALERTINGSOUNDID`    TINYINT UNSIGNED,
  `KEYLESSIGNITIONID`                TINYINT UNSIGNED,
  `SAEAUTOMATIONLEVEL_FROM`          TINYINT UNSIGNED,
  `AUTOREVERSESYSTEMID`              TINYINT UNSIGNED,
  `ACTIVESAFETYSYSNOTE`              VARCHAR(500),
  PRIMARY KEY (`ST_CASE`, `VEH_NO`),
  CONSTRAINT `fk_vpicdecode_crash_unit` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `crash_unit` (`ST_CASE`, `VEH_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `vpictrailerdecode` (
  `ST_CASE`                        INT UNSIGNED NOT NULL,
  `VEH_NO`                         TINYINT UNSIGNED NOT NULL,
  `TRAILER_NO`                     TINYINT UNSIGNED NOT NULL,
  `VEHICLEDESCRIPTOR`              VARCHAR(32),
  `VINDECODEDON`                   DATETIME,
  `VINDECODEERROR`                 VARCHAR(8),
  `VEHICLETYPEID`                  TINYINT UNSIGNED,
  `VEHICLETYPE`                    VARCHAR(8),
  `MANUFACTURERFULLNAMEID`         SMALLINT UNSIGNED,
  `MANUFACTURERFULLNAME`           VARCHAR(128),
  `MAKEID`                         SMALLINT UNSIGNED,
  `MAKE`                           VARCHAR(64),
  `MODELID`                        SMALLINT UNSIGNED,
  `MODEL`                          VARCHAR(255),
  `MODELYEAR`                      SMALLINT UNSIGNED,
  `SERIES`                         VARCHAR(64),
  `TRIM`                           VARCHAR(8),
  `PLANTCOUNTRYID`                 TINYINT UNSIGNED,
  `PLANTCOUNTRY`                   VARCHAR(32),
  `PLANTSTATE`                     VARCHAR(16),
  `PLANTCITY`                      VARCHAR(32),
  `PLANTCOMPANYNAME`               VARCHAR(64),
  `NOTE`                           VARCHAR(500),
  `BODYCLASSID`                    TINYINT UNSIGNED,
  `BODYCLASS`                      VARCHAR(32),
  `GROSSVEHICLEWEIGHTRATINGFROMID` TINYINT UNSIGNED,
  `GROSSVEHICLEWEIGHTRATINGFROM`   VARCHAR(64),
  `GROSSVEHICLEWEIGHTRATINGTOID`   TINYINT UNSIGNED,
  `GROSSVEHICLEWEIGHTRATINGTO`     VARCHAR(64),
  `TRAILERBODYTYPEID`              TINYINT UNSIGNED,
  `TRAILERBODYTYPE`                VARCHAR(64),
  `TRAILERTYPECONNECTIONID`        TINYINT UNSIGNED,
  `TRAILERTYPECONNECTION`          VARCHAR(32),
  `TRAILERLENGTHFT`                DECIMAL(5,3),
  `OTHERTRAILERINFO`               VARCHAR(500),
  `AXLESCOUNT`                     TINYINT UNSIGNED,
  `AXLECONFIGURATIONID`            TINYINT UNSIGNED,
  `AXLECONFIGURATION`              VARCHAR(8),
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `TRAILER_NO`),
  CONSTRAINT `fk_vpictrailerdecode_crash_unit` FOREIGN KEY (`ST_CASE`, `VEH_NO`)
    REFERENCES `crash_unit` (`ST_CASE`, `VEH_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------
-- Parked/working vehicle children (D3)
-- ----------------------------------------------------------------------

CREATE TABLE `pvehiclesf` (
  `ST_CASE`    INT UNSIGNED NOT NULL,
  `VEH_NO`     TINYINT UNSIGNED NOT NULL,
  `PVEHICLESF` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `PVEHICLESF`),
  CONSTRAINT `fk_pvehiclesf_accident` FOREIGN KEY (`ST_CASE`)
    REFERENCES `accident` (`ST_CASE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ----------------------------------------------------------------------
-- Person-level children
-- ----------------------------------------------------------------------

-- drugs: 748 exact-duplicate rows, so a surrogate key (D2)
CREATE TABLE `drugs` (
  `drug_id`    INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ST_CASE`    INT UNSIGNED NOT NULL,
  `VEH_NO`     TINYINT UNSIGNED NOT NULL,
  `PER_NO`     TINYINT UNSIGNED NOT NULL,
  `DRUGSPEC`   TINYINT UNSIGNED,
  `DRUGMETHOD` TINYINT UNSIGNED,
  `DRUGRES`    SMALLINT UNSIGNED,
  `DRUGQTY`    TINYINT UNSIGNED,
  `DRUGACTQTY` DECIMAL(9,3),
  `DRUGUOM`    TINYINT,
  PRIMARY KEY (`drug_id`),
  KEY `idx_drugs_person` (`ST_CASE`, `VEH_NO`, `PER_NO`),
  CONSTRAINT `fk_drugs_person` FOREIGN KEY (`ST_CASE`, `VEH_NO`, `PER_NO`)
    REFERENCES `person` (`ST_CASE`, `VEH_NO`, `PER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `miper` (
  `ST_CASE` INT UNSIGNED NOT NULL,
  `VEH_NO`  TINYINT UNSIGNED NOT NULL,
  `PER_NO`  TINYINT UNSIGNED NOT NULL,
  `P1`      TINYINT UNSIGNED,
  `P2`      TINYINT UNSIGNED,
  `P3`      TINYINT UNSIGNED,
  `P4`      TINYINT UNSIGNED,
  `P5`      TINYINT UNSIGNED,
  `P6`      TINYINT UNSIGNED,
  `P7`      TINYINT UNSIGNED,
  `P8`      TINYINT UNSIGNED,
  `P9`      TINYINT UNSIGNED,
  `P10`     TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `PER_NO`),
  CONSTRAINT `fk_miper_person` FOREIGN KEY (`ST_CASE`, `VEH_NO`, `PER_NO`)
    REFERENCES `person` (`ST_CASE`, `VEH_NO`, `PER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `nmcrash` (
  `ST_CASE` INT UNSIGNED NOT NULL,
  `VEH_NO`  TINYINT UNSIGNED NOT NULL,
  `PER_NO`  TINYINT UNSIGNED NOT NULL,
  `NMCC`    TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `PER_NO`, `NMCC`),
  CONSTRAINT `fk_nmcrash_person` FOREIGN KEY (`ST_CASE`, `VEH_NO`, `PER_NO`)
    REFERENCES `person` (`ST_CASE`, `VEH_NO`, `PER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `nmdistract` (
  `ST_CASE`    INT UNSIGNED NOT NULL,
  `VEH_NO`     TINYINT UNSIGNED NOT NULL,
  `PER_NO`     TINYINT UNSIGNED NOT NULL,
  `NMDISTRACT` TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `PER_NO`),
  CONSTRAINT `fk_nmdistract_person` FOREIGN KEY (`ST_CASE`, `VEH_NO`, `PER_NO`)
    REFERENCES `person` (`ST_CASE`, `VEH_NO`, `PER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `nmimpair` (
  `ST_CASE`  INT UNSIGNED NOT NULL,
  `VEH_NO`   TINYINT UNSIGNED NOT NULL,
  `PER_NO`   TINYINT UNSIGNED NOT NULL,
  `NMIMPAIR` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `PER_NO`, `NMIMPAIR`),
  CONSTRAINT `fk_nmimpair_person` FOREIGN KEY (`ST_CASE`, `VEH_NO`, `PER_NO`)
    REFERENCES `person` (`ST_CASE`, `VEH_NO`, `PER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `nmprior` (
  `ST_CASE`  INT UNSIGNED NOT NULL,
  `VEH_NO`   TINYINT UNSIGNED NOT NULL,
  `PER_NO`   TINYINT UNSIGNED NOT NULL,
  `NMACTION` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `PER_NO`, `NMACTION`),
  CONSTRAINT `fk_nmprior_person` FOREIGN KEY (`ST_CASE`, `VEH_NO`, `PER_NO`)
    REFERENCES `person` (`ST_CASE`, `VEH_NO`, `PER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `pbtype` (
  `ST_CASE`   INT UNSIGNED NOT NULL,
  `VEH_NO`    TINYINT UNSIGNED NOT NULL,
  `PER_NO`    TINYINT UNSIGNED NOT NULL,
  `PBAGE`     SMALLINT UNSIGNED,
  `PBSEX`     TINYINT UNSIGNED,
  `PBPTYPE`   TINYINT UNSIGNED,
  `PBCWALK`   TINYINT UNSIGNED,
  `PBSWALK`   TINYINT UNSIGNED,
  `PEDCTYPE`  SMALLINT UNSIGNED,
  `BIKECTYPE` SMALLINT UNSIGNED,
  `PEDLOC`    TINYINT UNSIGNED,
  `BIKELOC`   TINYINT UNSIGNED,
  `PEDPOS`    TINYINT UNSIGNED,
  `BIKEPOS`   TINYINT UNSIGNED,
  `PEDDIR`    TINYINT UNSIGNED,
  `BIKEDIR`   TINYINT UNSIGNED,
  `MOTDIR`    TINYINT UNSIGNED,
  `MOTMAN`    TINYINT UNSIGNED,
  `PEDLEG`    TINYINT UNSIGNED,
  `PEDSNR`    VARCHAR(3),
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `PER_NO`),
  CONSTRAINT `fk_pbtype_person` FOREIGN KEY (`ST_CASE`, `VEH_NO`, `PER_NO`)
    REFERENCES `person` (`ST_CASE`, `VEH_NO`, `PER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `per_aux` (
  `ST_CASE`   INT UNSIGNED NOT NULL,
  `VEH_NO`    TINYINT UNSIGNED NOT NULL,
  `PER_NO`    TINYINT UNSIGNED NOT NULL,
  `A_AGE3`    TINYINT UNSIGNED,
  `A_AGE6`    TINYINT UNSIGNED,
  `A_AGE7`    TINYINT UNSIGNED,
  `A_AGE8`    TINYINT UNSIGNED,
  `A_PTYPE`   TINYINT UNSIGNED,
  `A_RESTUSE` TINYINT UNSIGNED,
  `A_HELMUSE` TINYINT UNSIGNED,
  `A_ALCTES`  TINYINT UNSIGNED,
  `A_HISP`    TINYINT UNSIGNED,
  `A_RCAT`    TINYINT UNSIGNED,
  `A_HRACE`   TINYINT UNSIGNED,
  `A_EJECT`   TINYINT UNSIGNED,
  `A_PERINJ`  TINYINT UNSIGNED,
  `A_LOC`     TINYINT UNSIGNED,
  `A_DOA`     TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `PER_NO`),
  CONSTRAINT `fk_per_aux_person` FOREIGN KEY (`ST_CASE`, `VEH_NO`, `PER_NO`)
    REFERENCES `person` (`ST_CASE`, `VEH_NO`, `PER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `personrf` (
  `ST_CASE`  INT UNSIGNED NOT NULL,
  `VEH_NO`   TINYINT UNSIGNED NOT NULL,
  `PER_NO`   TINYINT UNSIGNED NOT NULL,
  `PERSONRF` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `PER_NO`, `PERSONRF`),
  CONSTRAINT `fk_personrf_person` FOREIGN KEY (`ST_CASE`, `VEH_NO`, `PER_NO`)
    REFERENCES `person` (`ST_CASE`, `VEH_NO`, `PER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- race: ORDER renamed RACE_ORDER (reserved word); MULTRACE lives in person (D8)
CREATE TABLE `race` (
  `ST_CASE`    INT UNSIGNED NOT NULL,
  `VEH_NO`     TINYINT UNSIGNED NOT NULL,
  `PER_NO`     TINYINT UNSIGNED NOT NULL,
  `RACE`       TINYINT UNSIGNED,
  `RACE_ORDER` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `PER_NO`, `RACE_ORDER`),
  CONSTRAINT `fk_race_person` FOREIGN KEY (`ST_CASE`, `VEH_NO`, `PER_NO`)
    REFERENCES `person` (`ST_CASE`, `VEH_NO`, `PER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `safetyeq` (
  `ST_CASE`  INT UNSIGNED NOT NULL,
  `VEH_NO`   TINYINT UNSIGNED NOT NULL,
  `PER_NO`   TINYINT UNSIGNED NOT NULL,
  `NMHELMET` TINYINT UNSIGNED,
  `NMPROPAD` TINYINT UNSIGNED,
  `NMOTHPRO` TINYINT UNSIGNED,
  `NMREFCLO` TINYINT UNSIGNED,
  `NMLIGHT`  TINYINT UNSIGNED,
  `NMOTHPRE` TINYINT UNSIGNED,
  PRIMARY KEY (`ST_CASE`, `VEH_NO`, `PER_NO`),
  CONSTRAINT `fk_safetyeq_person` FOREIGN KEY (`ST_CASE`, `VEH_NO`, `PER_NO`)
    REFERENCES `person` (`ST_CASE`, `VEH_NO`, `PER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
